[versions]
appcompat = "1.6.1"
asm-commons = "9.6"
auto-service = "1.1.1"
bcpkix-jdk15on = "1.70"
boringssl = "2.1"
cxx = "1.2.0"
gson = "2.10.1"
hiddenapibypass = "4.3"
nanohttpd = "2.3.1"
opencsv = "5.7.1"
recyclerview="1.3.2"
material = "1.10.0"
shisuku-version="12.2.0"
agp = "8.2.0"
wheelpicker = "1.1.3"
junit = "4.13.2"
junit-version = "1.1.5"
espresso-core = "3.5.1"
annotation= "1.3.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm-commons" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
auto-service-annotation = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkix-jdk15on" }
boringssl = { module = "io.github.vvb2060.ndk:boringssl", version.ref = "boringssl" }
cxx = { module = "dev.rikka.ndk.thirdparty:cxx", version.ref = "cxx" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
shisuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shisuku-version" }
shisuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shisuku-version" }
wheelpicker = { module = "cn.aigestudio.wheelpicker:WheelPicker", version.ref = "wheelpicker" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
camera2 = { module = "androidx.camera:camera-camera2", version.ref ="appcompat"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
annotation = { group= "androidx.annotation", name = "annotation", version.ref = "annotation"}

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }


